### ISSUE TITLE
invidio.us is deprecated, invidious.io should now be used

### ISSUE THREAD

**Issue by Mennaruuk** [belgianGeek/BadassBoard#16]
[According to the Invidious project](https://github.com/iv-org/invidious/issues/1694), the old invidio.us instance is now deprecated. The new official domain is **https://invidious.io**.

"The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/

https://git.invidious.io/ redirects to the Github page of the project: https://github.com/iv-org/invidious/

https://docs.invidious.io/ redirects to the documentation website of the project: https://github.com/iv-org/documentation/

https://invidious.io/ will become in the future a "project presentation" page (like https://searx.me/ ), we will use a markdown framework like Hugo."

**Comment by belgianGeek** [comment]
Hi @Mennaruuk !

Thank you for opening this issue. I've already updated the instances being used to [https://invidious.fdn.fr](https://invidious.fdn.fr) and [https://invidious.kavin.rocks](https://invidious.kavin.rocks) as mentioned in this final commit from last October 26b0a15.

If you have any question or advice to give me regarding this specific commit or the whole project, feel free ! :wink:

**Comment by Mennaruuk** [comment]
Thank you :)
